### ISSUE TITLE
Not Found Airdrop Command

### ISSUE THREAD

**Issue by saito-kosuke** [GenesysGo/shadow-drive#15]
**Current Behavior**
When execution of the following command,
`shdw-drive airdrop-shdw -r <any wallet address>`
the output as follows show.
```
This is beta software. Use at your own discretion.
error: unknown command 'airdrop-shdw'
```

**Expected Behavior**
We should add `airdrop-shdw` command.

**Comment by tracy-codes** [comment]
This is not a command that will be added, you are not allowed free SHDW. Closing.

**Comment by saito-kosuke** [comment]
@tracy-codes 
I can't use this command on devnet too.

> This is not a command that will be added

If so, we should remove the section as follows.

https://shdw.genesysgo.com/using-shadow-drive/the-shadow-drive-platform/shadow-drive-cli#devnet-testing-only-request-usdshdw-airdrop

**Comment by tracy-codes** [comment]
Noted, will remove it. Thank you.
