### ISSUE TITLE
Can't Upload a File via both CLI and SDK

### ISSUE THREAD

**Issue by saito-kosuke** [GenesysGo/shadow-drive#16]
*Current Behavior*
When executing the following command,
`shdw-drive upload-file --keypair ~/.config/solana/id.json --file ./assets/0.png `
the following output shows.
```
This is beta software. Use at your own discretion.
✔ Which storage account do you want to use? › SAITO test - 2Rq...MxJ - 9.81 MB remaining
✖ Error processing transaction. See below for details:
Server response status code: 400
Server response status message: Error: failed to send transaction: Transaction simulation failed: Error processing Instruction 0: custom program error: 0x1
```
The same goes for SDK.

*Expected Behavior*
1. The error message is not appropriate. The status code 400 is used as "Not Found Error" in general, but some transactions have failed actually.
2. Fix the problem to upload a file.

**Comment by tracy-codes** [comment]
0x1 error means your wallet is not funded with enough SOL to make the transaction happen.

Along with that, 400 error is not a not found, it means "bad request" in general. We could swap it out for 500 if that's more ideal.

**Comment by saito-kosuke** [comment]
@tracy-codes 

> Along with that, 400 error is not a not found, it means "bad request" in general. 

I misunderstood, I'm sorry. You're right.

> 0x1 error means your wallet is not funded with enough SOL to make the transaction happen.

**Comment by tracy-codes** [comment]
0x1 is a Solana error code, it's not specific to our program.

https://stackoverflow.com/questions/68450242/i-want-to-know-causing-a-solana-transfer-error

**Comment by saito-kosuke** [comment]
@tracy-codes Thank you for taking your time. Noted.
Can I give you other feedback?

Sometimes the error as follows occurs, but I can't see the error message.
```
Server response status code: 400 
Server response status message: "[object Object]"
```

**Comment by tracy-codes** [comment]
Our next release will resolve this.

**Comment by saito-kosuke** [comment]
I'm developing the integration with the Metaplex candy machine v2.
I will try your next release, so I close the issue.
