### ISSUE TITLE
Cannot delete v2 files

### ISSUE THREAD

**Issue by bntzio** [GenesysGo/shadow-drive#47]
**SDK version**: 3.0.4
**Platform**: Web (JS)

Whenever you try to delete a file using the `deleteFile` method, it throws the following error:

```
Cannot read properties of undefined (reading 'owner-account-pubkey')
```

That is when attempting to delete a file stored on a v2 storage account using the following method call:

```
deleteFile(account, url, 'v2')
```

Now, when trying to delete a file stored on a v1 storage account using the `deleteFile` method and passing the `v2` version as the parameter as:

```
deleteFile(account, url, 'v2')
```

It throws the following error:

```
Invalid account discriminator
```

However, when trying setting the version to v1 as:

```
deleteFile(account, url, 'v1')
```

To further attempt to delete a file stored on a v1 storage account, the signature request pops up, and when approving it, the file gets successfully deleted, which makes sense as its a file stored on a v1 storage account.

What it's weird is that it worked with a signature request (not a transaction) and it's a v1 file, and v2 files are failing with either the v1 and v2 parameters.

**Comment by tracy-codes** [comment]
This should be resolved!
