### ISSUE TITLE
Available storage bytes not updating after decreasing or increasing storage

### ISSUE THREAD

**Issue by bntzio** [GenesysGo/shadow-drive#48]
**SDK version**: 3.0.4
**Platform**: Web (JS)

When decreasing or increasing storage on accounts, the available storage (`account.storageAvailable`) is not updating.

This is when calling the following methods:

```
addStorage(account, '5MB', 'v1')
reduceStorage(account, '3MB', 'v1')
```

Decreasing from 10MB to 7MB:
![CleanShot 2022-07-16 at 00 36 37](https://user-images.githubusercontent.com/3136873/179341434-366b232d-2287-4d4c-b754-fa96ec942fa6.png)
![CleanShot 2022-07-16 at 00 36 44](https://user-images.githubusercontent.com/3136873/179341436-0fcc367c-ccb4-4b6c-9686-f42368ab0884.png)
 
Increasing from 7MB to 12MB:
![CleanShot 2022-07-16 at 00 39 05](https://user-images.githubusercontent.com/3136873/179341716-2ce86dd3-4ada-47d9-b85a-129d4ed3c1fa.png)
![CleanShot 2022-07-16 at 00 39 22](https://user-images.githubusercontent.com/3136873/179341718-225348fa-8d88-45dc-aac3-f27bde8f2710.png)

Here's the storage account public key for reference: `4q947fGHu18vyedSSVFqzW5QjyfXMWmCgkWzm3jDxPTE`

**Comment by khaIilnafis** [comment]
This issue is on the program side, storage is updated on the struct when those instructions are called but storage available isn't currently. Will discuss with the team if we'll update this. 

To accurately get the storage available for a v1 account you'll want to use the get-storage-account method in the SDK or invoke the API directly to call storage-account-info.

**Comment by bntzio** [comment]
> This issue is on the program side, storage is updated on the struct when those instructions are called but storage available isn't currently. Will discuss with the team if we'll update this.
> 
> To accurately get the storage available for a v1 account you'll want to use the get-storage-account method in the SDK or invoke the API directly to call storage-account-info.

Ok I'll try that 👍
