### ISSUE TITLE
Cannot make v1 storage accounts immutable

### ISSUE THREAD

**Issue by bntzio** [GenesysGo/shadow-drive#49]
**SDK version**: 3.0.4
**Platform**: Web (JS)

When calling the following method on a v1 storage account:

```
makeStorageImmutable(publicKey, 'v1')
```

It throws the following error:

```
Server response status code: 400

Server response status message: "Error: failed to send transaction: Transaction simulation failed: Error processing Instruction 0: custom program error: 0xbba"
```

V2 storage accounts works good.

**Comment by khaIilnafis** [comment]
Was this run with a v1 account created prior to release of v1.5?

**Comment by bntzio** [comment]
> Was this run with a v1 account created prior to release of v1.5?

Yes

**Comment by tracy-codes** [comment]
This should be resolved now.
