### ISSUE TITLE
CORS preflight error on http & https when calling `createStorageAccount`

### ISSUE THREAD

**Issue by cloakd** [GenesysGo/shadow-drive#5]
When attempting to create a storage account on web frontend its rejecting due to blocked `content-type` header field on the preflight check. Should just be a matter of adding it to AllowHeaders on nginx/endpoint config.

Calling code:
```js
this.drive.createStorageAccount("Example", "1MB");
```

Endpoint: [POST] https://shadow-storage.genesysgo.net/storage-account
Status code: (Failing on preflight so no status) - CORS Error
Error: `Access to fetch at 'https://shadow-storage.genesysgo.net/storage-account' from origin 'https://jovial-gingersnap-4394fd.netlify.app' has been blocked by CORS policy: Request header field content-type is not allowed by Access-Control-Allow-Headers in preflight response.`

Request (Images come from an earlier test on localhost but same result on the https endpoint):
![image](https://user-images.githubusercontent.com/2733949/168424110-fd8d5c45-2624-473a-bd15-6054dca1375b.png)
![image](https://user-images.githubusercontent.com/2733949/168424114-174963a5-67c4-4b6a-8b78-c45d10172436.png)
![image](https://user-images.githubusercontent.com/2733949/168424118-72097110-5e0d-4dd8-acd9-e42d02fbc361.png)

**Comment by khaIilnafis** [comment]
Thanks for reporting, we're resolving this now. Will post an update here once that is fully rolled out.

**Comment by khaIilnafis** [comment]
This has been resolved @cloakd. Let us know if you face anything else.
