### ISSUE TITLE
Dead link to Node examples

### ISSUE THREAD

**Issue by numisman** [GenesysGo/shadow-drive#56]
https://github.com/GenesysGo/shadow-drive/blob/537c381dbe3d7b91b30a73fd9cd6c15ce7cd7764/README.md?plain=1#L56

Are there Node examples that weren't deployed and this is just a placeholder?  Or is this a need for the repo?

**Comment by khaIilnafis** [comment]
Removed dead link

**Comment by numisman** [comment]
Thanks!
