### ISSUE TITLE
File size are not listing with files name.

### ISSUE THREAD

**Issue by hussammustafa** [GenesysGo/shadow-drive#57]
Hi, I am using this package. I need to show file size as well when we call listObjects using this package. or any other function available for that please let me know.

**Comment by tracy-codes** [comment]
Please see the API documentation at https://shdw.genesysgo.com/using-shadow-drive/the-shadow-drive-platform/shadow-drive-api.

POST /list-objects-and-sizes is what you're looking for.

**Comment by hussammustafa** [comment]
Yes, But I am using sdk for getting that. 
And can you tell, how we can get the drive size information ?
