### ISSUE TITLE
Type issue on delete

### ISSUE THREAD

**Issue by robbestad** [GenesysGo/shadow-drive#58]
https://github.com/GenesysGo/shadow-drive/blob/537c381dbe3d7b91b30a73fd9cd6c15ce7cd7764/src/methods/delete-file.ts#L19
https://github.com/GenesysGo/shadow-drive/blob/537c381dbe3d7b91b30a73fd9cd6c15ce7cd7764/src/methods/delete-file.ts#L74

This operation says it returns a `txid` as `ShadowDriveResponse` but it returns a `message` on success. So in order to correctly type I had to do this:
```
interface ExtendedShadowDriveResponse extends ShadowDriveResponse{
        message?:string
    }
```

**Comment by khaIilnafis** [comment]
Thanks for reporting, will get this updated.

**Comment by tracy-codes** [comment]
@khaIilnafis Can you please check into if this change is still needed?

**Comment by khaIilnafis** [comment]
Will resolve in next release.
