### ISSUE TITLE
UploadFile does not accept browser FormData (getBuffer is not a function)

### ISSUE THREAD

**Issue by cloakd** [GenesysGo/shadow-drive#6]
Hey guys, it looks like the `uploadFile` function is expecting the node version of `FormData`  so is erroring due to missing buffer function for the payload. I have tried with both native `FormData` & NPM form-data package but get the same error:
```
File upload error TypeError: data.getBuffer is not a function
    at ShdwDrive.eval (upload-file.js?7010:53:1)
    at Generator.next (<anonymous>)
    at fulfilled (upload-file.js?7010:28:1)
```

Native FormData:
![image](https://user-images.githubusercontent.com/2733949/168530339-eb9c4737-cc02-4d82-9eb8-5397a6c8cfef.png)

**Comment by DataKnox** [comment]
I can also recreate this issue when attempting to upload via browser. I have not tested in Node yet

**Comment by khaIilnafis** [comment]
Opened to address this: https://github.com/GenesysGo/shadow-drive/pull/8
