### ISSUE TITLE
reduce-storage returns HTTP 400 Blockhash not found

### ISSUE THREAD

**Issue by jokumusic** [GenesysGo/shadow-drive#70]
I'm using the SDK. addStorage works fine on the same storage account, but reduceStorage fails.
Given the same pubkey:

await drive.addStorage(pubkey, incrementSizeUnited, "v2") //works
await drive.reduceStorage(pubkey, size, "v2") //fails with Blockhash not found

**Comment by tracy-codes** [comment]
Hi! This is an issue on the Solana RPC side. Unfortunately all you can do is retry the methods.
