### ISSUE TITLE
Can't import the named export 'Keypair' from non EcmaScript module

### ISSUE THREAD

**Issue by Jrejoire** [GenesysGo/shadow-drive#73]
Good evening,

Trying to use the sdk in a React application. I followed the README setup on the client side but get the following error in the terminal:
`Failed to compile.

./node_modules/@shadow-drive/sdk/node_modules/@solana/spl-token/lib/esm/actions/createMint.mjs
Can't import the named export 'Keypair' from non EcmaScript module (only default export is available)`

Here is the screenshot of the code in my component:
![image](https://user-images.githubusercontent.com/33304306/206877078-fd875b05-f636-4841-a22d-1ab08066af6a.png)

In the browser console, I get a slightly different error:
`Can't import the named export 'u8' from non EcmaScript module (only default export is available)`

![image](https://user-images.githubusercontent.com/33304306/206877008-571dafd2-9295-4c43-8403-a9df35ba908d.png)

I tried version 3.0.10 and 3.0.8 of the sdk so far.
Hope you can help. I'll try now on the back end instead.

**Comment by tracy-codes** [comment]
Hi! Apologies for the delay on getting a response here. Are you still experiencing this issue?

**Comment by khaIilnafis** [comment]
Looks like this may be a version mismatch issue w/ something in @solana/spl-token. Can take a look
