### ISSUE TITLE
drive.createStorageAccount returns "Server response status message: Timed out awaiting confirmation on transaction"

### ISSUE THREAD

**Issue by yilmazbingo** [GenesysGo/shadow-drive#75]
I need to upload photos to shadow drive. this is the complete code. all you need is to create a `.ts` file and run `ts-node filename`. this  is the version ` "@shadow-drive/sdk": "^3.0.10"`

    import { ShdwDrive } from "@shadow-drive/sdk";
    import { clusterApiUrl, Connection, Keypair } from "@solana/web3.js";
    import * as anchor from "@project-serum/anchor";
    import fs from "fs";
    
    function loadKeypairFromFile(filename: string): Keypair {
      const secret = JSON.parse(fs.readFileSync(filename).toString()) as number[];
      const secretKey = Uint8Array.from(secret);
      return Keypair.fromSecretKey(secretKey);
    }
    
    const payer = loadKeypairFromFile(
        // generate file `solana-keygen grind --starts-with NFT:1`
      "NFTqksZ3jKr78fHYnJnw1QTwDavQrD7MAzfaGL3Xpij.json"
    );
    const connection = new Connection(clusterApiUrl("devnet"));
    async function airdrop() {
      await connection.requestAirdrop(oayer.publicKey, 1e9);
      let balance = await connection.getBalance(payer.publicKey);
      console.log(balance);
    }
    // docs uses anchor wallet
    const wallet = new anchor.Wallet(payer);
    
    // airdrop();
    
    async function createShadowAccount(): Promise<string | undefined> {
      try {
        const drive = await new ShdwDrive(connection, wallet).init();
        // this logs succesfully
        // console.log("drive", drive); 
        const result = await drive.createStorageAccount("super", "100MB", "v2");
        console.log("result", result);
        return result.shdw_bucket;
      } catch (error) {
        console.error("error", error);
      }
    }
    createShadowAccount();

code runs till `await drive.createStorageAccount("super", "100MB", "v2")` line. it hangs here for a couple of minutes and then logs the error message. I passed correct types to the the function.

[npm docs][1] says in case of 400 post errors use this:

    const connection = new solanaWeb3.Connection(
        "https://ssc-dao.genesysgo.net/",
    	"max"
      );

But this returns 

    error Error: failed to get info about account 7j4DNsnZ4KeCsM46yFu4S3fPtzSnVi1ZRc6iiRPETXCA: 
    Error: 403 Forbidden: Authentication missing.

  [1]: https://www.npmjs.com/package/@shadow-drive/sdk

**Comment by tracy-codes** [comment]
Hi, that RPC endpoint is now deprecated. Thank you for flagging that from the NPM docs.

As for the `Server response status message: Timed out awaiting confirmation on transaction` error, this is a solana transaction error meaning the transaction timed out while attempting to submit to the validator cluster. All that can be done is to sign and submit a new transaction to try it again.

**Comment by yilmazbingo** [comment]
@tracy-codes I tried the code since yesterday, but still same error. there is no transaction signature.  I think the only transaction is being done by the `shadow drive`. This code is failing

       const result = await drive.createStorageAccount("super", "100MB", "v2");

**Comment by tracy-codes** [comment]
> @tracy-codes I tried the code since yesterday, but still same error. there is no transaction signature. I think the only transaction is being done by the `shadow drive`. This code is failing
> 
> ```
>    const result = await drive.createStorageAccount("super", "100MB", "v2");
> ```

Do you mind trying again? We just resolved a few errors on the server-side that might've been related to this.

**Comment by MathieuCesbron** [comment]
If I understand correctly, there is no devnet RPC. `const connection = new Connection(clusterApiUrl("devnet"));` will not work, is that right ?

`const connection = new Connection(clusterApiUrl("mainnet-beta"));` does not work for me in React, does it work for you if you make this change @yilmazbingo ?

**Comment by tracy-codes** [comment]
There is no devnet availability for shadow drive, no. This is in the documentation as well.

**Comment by yilmazbingo** [comment]
@MathieuCesbron  using "mainnet-beta" does not work neither.
