### ISSUE TITLE
getStorageAccounts is disabled ?

### ISSUE THREAD

**Issue by MathieuCesbron** [GenesysGo/shadow-drive#76]
Hi,

It looks like `getStorageAccounts` is disabled, I succeed to create storages but I cant GET them with the sdk. Is it normal ? Is there another endpoint ?

```
...
const accts = await drive.getStorageAccounts("v2");
console.log("accts: ", accts);

{"jsonrpc":"2.0","error":{"code": 410, "message":"The RPC call or parameters have been disabled."}, "id": "dba326d4-032e-4d77-8881-b9cfeef55a41" }
```

**Comment by tracy-codes** [comment]
@MathieuCesbron Hi, what RPC do you have configured? Or are you using the default one that's set which is `api.mainnet-beta.solana.com`? Also, are you using this in a node.js environment or React?

Please also provide what version of the SDK you're using.

**Comment by MathieuCesbron** [comment]
Hello, I have the default RPC: `api.mainnet-beta.solana.com`. I use the version `3.0.8`.

I tried it both on node.js and React and I have the same output. By the way, it works with `getStorageAccount(<public key of storage account>)` so just `getStorageAccounts` is not working for me.

**Comment by tracy-codes** [comment]
It looks like we're using getProgramAccounts in that method and the free solana mainnet rpc is heavily limited. You will need to supply a new rpc endpoint that isn't the free public endpoint, there's nothing we can do about that.
