### ISSUE TITLE
createStorageAccount need a paid RPC ?

### ISSUE THREAD

**Issue by MathieuCesbron** [GenesysGo/shadow-drive#77]
When I use `createStorageAccount` on a node script it works well but in React app I have the following error:

```Error: failed to get info about account BKde9yZsdt7ek4eHi5ZYwp89w7AnAsahDaT5TAof2hXn: Error: 403 :  {"jsonrpc":"2.0","error":{"code": 403, "message":"Access forbidden, contact your app developer or support@rpcpool.com."}, "id": "1187b424-310c-41c8-8c69-2ed93b50d563" } ```

My node script looks the same as my React app, am I missing something ? Is there a limitation when we used it from the browser ? It feels like I need to use a paid RPC.

**Comment by tracy-codes** [comment]
Hi, by default the rpc used is the solana mainnet rpc `api.mainnet-beta.solana.com`. If you're getting blocked by that, you'll have to sign up for a paid RPC. We can't control how the solana mainnet rpc endpoint is limited. 

You can sign up for a premium, unlimited RPC at https://portal.genesysgo.net/premium/rpcs or you can use another RPC provider of your choice.
