### ISSUE TITLE
Example on how to upload a file from react by creating the File object ?

### ISSUE THREAD

**Issue by MathieuCesbron** [GenesysGo/shadow-drive#82]
Hey,

In the Doc (https://docs.genesysgo.com/shadow/shadow-drive/the-sdk), there is an example on how to upload a file with React with an input file.

I would like create a File object on my react app and to upload it.

I have:

```javascript
const uploadFile = await drive.uploadFile(
  new PublicKey(shdwHash),
  new File(["test"], "test.json"),
  "v2",
);
```

I get the error:  ```error: TypeError: Cannot read properties of undefined (reading 'secretKey')```. I can't figure what I am doing wrong, can you help me ?

I am on version ```3.0.10```.

BTW Shadow is great, thanks guys 🥇

**Comment by khaIilnafis** [comment]
Hi Mathieu,

This issue most likely stems from the ShdwDrive instance having been created prior to the wallet-provider being ready. In the latest example on main branch you can see a slight change in dependency in the useEffect that creates the drive instance, which may resolve your issue.

Additionally we've released a new version of the sdk 3.1.0 (should be unrelated to what you're seeing.)

**Comment by MathieuCesbron** [comment]
I tested on the latest example on main branch. I changed  [(here in the example) ](https://github.com/GenesysGo/shadow-drive/blob/main/examples/web/src/Drive.tsx#L57) to:

```javascript
const files: ShadowFile[] = [
  { name: "test.json", file: Buffer.from(JSON.stringify({ ama: "test" })) },
];

const uploadResponse = await drive.uploadMultipleFiles(
  new PublicKey("AdSA1249vEWYX7pW9ybP7eb6WeDZvvxRDqbgJz9AdGcf"),
  files,
```

And I get a new error: 
```
TypeError: Failed to execute 'append' on 'FormData': parameter 2 is not of type 'Blob'.
    at ShdwDrive.<anonymous> (upload-multiple-files.ts:77:1)
    at Generator.next (<anonymous>)
    at upload-file.ts:15:1
    at new Promise (<anonymous>)
    at __webpack_modules__../node_modules/@shadow-drive/sdk/dist/methods/upload-multiple-files.js.__awaiter (upload-file.ts:15:1)
    at ShdwDrive.uploadMultipleFiles (upload-multiple-files.ts:36:1)
    at listItemHandler (ListItem.tsx:72:1)
```

I must be doing something wrong.

**Comment by tracy-codes** [comment]
Maybe try converting the file data buffer to a Blob? Something like `new Blob([Buffer.from("data")])`

**Comment by MathieuCesbron** [comment]
Thanks, I succeeded with:

```javascript    
const itemJSONBlob = new Blob(
      [
        JSON.stringify({
              key: "value"
        }),
      ],
      {
        type: "application/json",
      },
    );
```
