### ISSUE TITLE
How to ask the user to sign a shadow transaction and another random transaction ?

### ISSUE THREAD

**Issue by MathieuCesbron** [GenesysGo/shadow-drive#84]
Hey,

I would like to ask the user on the frontend to sign a shadow transaction (uploading a file for example) AND to sign another transaction that is not related to Shadow at the same time, is this possible ? Is there an example on how to do it ?

I don't want to ask the user to confirm a transaction on his wallet twice. 

Have a good day,

**Comment by tracy-codes** [comment]
Currently the shadow network expects the shadow drive-specific transaction to only have instruction related to the shadow drive on chain program. Any other instructions will cause it to fail. This is an intended security measure to ensure users aren't sending in malicious transactions.

**Comment by MathieuCesbron** [comment]
I understand, thanks for the answer.
