### ISSUE TITLE
Upload not working in React component using wallet adapter

### ISSUE THREAD

**Issue by Woody4618** [GenesysGo/shadow-drive#87]
Hello, 
i am using wallet adapter with the example from the docs. 
Creating a new storage account works, I can sign it with phantom wallet but uploadFile throws this error: 

<img width="552" alt="image" src="https://user-images.githubusercontent.com/5938789/224010156-1f45d333-53b3-4ae7-b975-329a2b5a61ab.png">

Do i need to pass in a private key and create a local wallet? That would mean I can not use it in combination with just the wallet adapter?  

This is the code: 
`    
    const [file, setFile] = useState<File>(undefined)
    const [uploadUrl, setUploadUrl] = useState<String>(undefined)
    const [txnSig, setTxnSig] = useState<String>(undefined)
    const wallet = useAnchorWallet();

const onSubmit = async (event: any) => {

        event.preventDefault()

        const drive = await new ShdwDrive(CONNECTION, wallet as AnchorWallet).init();

        const accounts = await drive.getStorageAccounts("v2");
        const acc = accounts[0].publicKey;
        const getStorageAccount = await drive.getStorageAccount(acc);

        const upload = await drive.uploadFile(acc, file);
        console.log(upload);
        setUploadUrl(upload.finalized_locations)
        setTxnSig(upload.transaction_signature)
        
    }
`

**Comment by Woody4618** [comment]
So looks like AnchorWallet does not support signMessage in walletAdapterReact 🤔

**Comment by GummersGG** [comment]
Thank you for letting us know. We will make the needed updates in the docs.

**Comment by tracy-codes** [comment]
@GummersGG please reopen this issue as it may be a bug that requires some attention.

**Comment by tracy-codes** [comment]
> Ok I fixed it, looks like the docs where outdated. When I just pass in wallet instead of AnchorWallet it works since wallet implements signMessage: const wallet = useWallet(); const drive = await new ShdwDrive(CONNECTION, wallet).init();

@Woody4618 Can you please share a link of the example you were working from that had `wallet as AnchorWallet` for react? Our web example for react and the readme both don't use this.

**Comment by Woody4618** [comment]
Hey, i followed the instructions here: https://docs.genesysgo.com/shadow/shadow-drive/the-sdk
