### ISSUE TITLE
"TypeError: source.on is not a function" when uploading files

### ISSUE THREAD

**Issue by kromsten** [GenesysGo/shadow-drive#88]
Trying to upload multiple files using Shadow Drive on SvelteKit backend. 

Everything  works perfectly in development with
```bash
vite dev
```

However when trying to move to production using @sveltejs/adapter-node with
```bash
vite build
node build/index.js
```
node server crashes due to an error thrown by shadow drive package:
```
TypeError: source.on is not a function
1|prod  |     at DelayedStream.create (/***/node_modules/delayed-stream/lib/delayed_stream.js:33:10)
1|prod  |     at CombinedStream.append (/***/node_modules/combined-stream/lib/combined_stream.js:45:37)
1|prod  |     at FormData.append (/***/node_modules/@shadow-drive/sdk/node_modules/form-data/lib/form_data.js:75:3)
1|prod  |     at ShdwDrive.<anonymous> (/***/node_modules/@shadow-drive/sdk/dist/methods/upload-multiple-files.js:80:22)
1|prod  |     at Generator.next (<anonymous>)
1|prod  |     at /***/node_modules/@shadow-drive/sdk/dist/methods/upload-multiple-files.js:31:71
1|prod  |     at new Promise (<anonymous>)
```

You can reproduce it by creating a setup where you upload files using .uploadMultipleFiles() on the server side.
E.g.
https://github.com/kromsten/emancipate/blob/main/src/routes/upload/%2Bserver.ts

**Comment by tracy-codes** [comment]
Hi! Our team isnt familiar with sveltekit backend. If find a way to patch this issue, please submit a PR and we'll look into merging it in.
